sudo: false
language: python
install:
- pip install -r test-requirements.txt
script:
- tox
after_success:
- codecov
jobs:
  include:
  - stage: test
    python: 3.6
    env: TOXENV=formatting,py36
  - stage: test
    python: 3.5
    env: TOXENV=py35
  - stage: deploy
    python: 3.6
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: G4BJpzI55W0ttnz2gVQ3PwnEFgsaYx8ek5yD0eL7y0v2l7UTYnQLGX+fP15mEfdJf1CSyogHROexOZ6H8Se17JFbmEJilcVHcoJLYaqxLTWU3Mpk5hf9uvD47Ran2GR08LosPv7kJMDAB/pqudtOHrNPhgVvfnhJZSXOZdyRV6ZUiN5rb6sbXRh9wKzszuqYh6ue+PEgINW1ezQCIKnb8d//ldkgNV5N/IRIEzI/60DCXe2BgbCvIiVsEUbSvCEli6QE8nb9VIY3W8LhZGB6azeqIhXkdm/7BGXujIckP5xTb4WwkNGOtlZbQNdRvFMksaKs61FJHa7Gs8YX1/xdClVuOAvJPR4EvLlSusKeOfA5Yqah0T+EW26r77GOlm5+L//d8I084UZxnj+mg3BJLUIXKLH+ofrYNAheJRiAEWbO5wsF3NA30/ncIvW8x4rQoJSgfVh1dNrHLBe6NophsZYGB20NSTsjjqKeatDGW1/Aej4Z4Sw8CCz9EGSDtFAjYz6o2kMla47AU+wNl7RyjMsGvJ2kAEpso3VUZHJvCCd34hQtjBcBw7CNuQWSBCfKAcS/W9fkw/CED+9Y5Dkcln+oqAraO+i84snSEql4t2wfm+8OlpvkwJcZ7VWATjPbyD+XCRpBErMdJatPHnAgUUeT7kV6uxCnNOwfGPlqIXg=
      on:
        tags: true
        distributions: sdist bdist_wheel
        repo: madedotcom/striemann
